activespring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    # Admin panel URL

    path('admin/', admin.site.urls),

    # Bookings app URLs

    path('', include('bookings.urls'), name="bookings_urls"),

    # Webpages URLs

    path('webpages/', include('webpages.urls'), name='webpages_urls'),

    # Accounts URLs

    path('accounts/', include('allauth.urls')),

]

bookings/urls.py
from . import views

from django.urls import path

app_name = 'bookings'

urlpatterns = [

    # Index page URL

    path('', views.index_page, name='index'),

    # Booking page URL

    path('booking/', views.booking_home, name='booking'),

    # Create booking page URL

    path('create-booking', views.create_booking, name='create'),

    # Update booking page URL

    path('update-booking/<str:booking_id>/', views.update_booking, name='update'),

    # Delete booking URL

    path('delete-booking/<str:booking_id>/', views.delete_booking, name='delete'),

]

webpages/urls.py
from . import views
from django.urls import path


app_name = 'webpages'


urlpatterns = [
    # Contact Us URL

    path('contact-us/', views.contact_us, name='contact-us'),

    # Sauna Steam URL

    path('sauna-steam/', views.SaunaSteam.as_view(), name='sauna-steam'),

]

bookings/models.py
from django.db import models

from django.contrib.auth.models import User

from phonenumber_field.modelfields import PhoneNumberField

from django.core.validators import MaxValueValidator, MinValueValidator

import datetime

pool_timings = (
    ('08:00', '08:00'),
    ('09:00', '09:00'),
    ('10:00', '10:00'),
    ('11:00', '11:00'),
    ('12:00', '12:00'),
    ('13:00', '13:00'),
    ('14:00', '14:00'),
    ('15:00', '15:00'),
    ('16:00', '16:00'),
    ('17:00', '17:00'),
    ('18:00', '18:00'),
)
pool_status = (

    ('Pending', 'Pending'),

    ('Confirmed', 'Confirmed'),

    (
        'Rejected, try booking on a different hour',
        'Rejected, try booking on a different hour',
    ),
)


class Booking(models.Model):
    "The booking model"

    booking_id = models.AutoField(primary_key=True)

    name = models.CharField(max_length=200, blank=False, default="")

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='customer', null=True)

    email = models.EmailField(max_length=254)

    no_of_persons = models.IntegerField(
        default=1, validators=[MinValueValidator(1), MaxValueValidator(100)])

    booking_date = models.DateField()

    booking_time = models.CharField(
        max_length=10, default='08:00', choices=pool_timings)

    phone_number = PhoneNumberField(blank=True, null=True)

    booking_status = models.CharField(
        max_length=50, choices=pool_status, default="Pending")

    booked_on = models.DateTimeField(auto_now_add=True)

    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-booked_on']

    def __str__(self):
        return str(self.name)

webpages/models.py
from django.db import models

# Create your models here.

bookings/forms.py
from django.forms import ModelForm, EmailInput, NumberInput, TextInput

from django import forms

from bookings.models import Booking


class DateInput(forms.DateInput):
    input_type = 'date'


class CustomerForm(forms.ModelForm):

    class Meta:

        model = Booking

        fields = '__all__'

        exclude = ['booked_on', 'approved', 'booking_status', 'user']

        widgets = {
            'booking_date': DateInput(),
            'email': EmailInput(attrs={
                'placeholder': 'Email'}),
            'phone_number': NumberInput(attrs={
                'placeholder': '+44XXXXXXXXXX'
            }),
            'name': TextInput(attrs={
                'placeholder': 'Full Name'
            }),
        }

bookings/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse

from django.core.paginator import Paginator

from .models import Booking

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

from django.contrib import messages

from .forms import CustomerForm


# Home page view

def index_page(request):

    return render(request, 'bookings/index.html')


# Create booking view

@login_required(login_url="account_login")
def create_booking(request):
    """ This view gives users the ability to create bookings"""

    # Set form variable to CustomerForm
    form = CustomerForm()

    # Check if request equal to POST
    if request.method == 'POST':

        # Pass in POST request
        form = CustomerForm(request.POST)

        # Check if the form is valid before submit
        if form.is_valid():

            # Postpone save
            customer = form.save(commit=False)

            # Set Foreign key to user
            customer.user = request.user

            # Save to current user
            customer.save()

            # Displays successful message to user
            messages.add_message(
                request, messages.SUCCESS,
                'Your booking has been successfully created!')

            # Redirect back to booking.html
            return redirect(reverse('bookings:booking'))

    # Pass form into context dictionary
    context = {'form': form}

    # Return and render create-booking.html
    return render(request, 'bookings/create-booking.html', context)


# Booking home view

def booking_home(request):
    """ This view give users the ability to view their bookings"""

    # Get logged-in user ID
    current_user = request.user.id

    # Filter user objects from database in relation to foreign key
    customer = Booking.objects.all().filter(user=current_user)

    # Set Paginator to 3 on customer
    paginator = Paginator(customer, 3)

    # Get the page number request
    page_number = request.GET.get('page')

    # Get page numbers for paginator
    page_obj = paginator.get_page(page_number)

    # Place page_obj into context dictionary
    context = {'page_obj': page_obj}

    # Return and render booking.html
    return render(request, 'bookings/booking.html', context)


# Update booking view

@login_required(login_url="account_login")
def update_booking(request, booking_id):
    """ This view gives users the ability to update their bookings"""

    if not request.user.is_authenticated:

        messages.error(request, 'Sorry, you need to be logged in.')

        return redirect(reverse('account_login'))

    # Get booking_id that's pass in by url
    customer = get_object_or_404(Booking, booking_id=booking_id)

    if customer in request.user.customer.all():

        # pass customer as a instance into Customer form
        form = CustomerForm(instance=customer)

        # Check if request equal to POST
        if request.method == 'POST':

            # Pass in the type request and the customer instance
            form = CustomerForm(request.POST, instance=customer)

            # check if the form is valid
            if form.is_valid():

                # save the form
                form.save()

                # Display successful message to user
                messages.add_message(
                    request, messages.SUCCESS,
                    'Your booking has been successfully updated!')

                # Redirect back to booking.html
                return redirect(reverse('bookings:booking'))

        # Pass form into context dictionary
        context = {'form': form}

        # Return and render update-booking.html
        return render(request, 'bookings/update-booking.html', context)

    else:
        messages.error(request, 'Sorry, you are not allow on this page!')

        return redirect(reverse('bookings:index'))


# Delete booking view

@login_required(login_url="account_login")
def delete_booking(request, booking_id):
    """ This view gives users the ability to delete their bookings"""

    if not request.user.is_authenticated:

        messages.error(request, 'Sorry, you need to be logged in.')

        return redirect(reverse('account_login'))

    # Get booking_id that's pass in by url
    customer = get_object_or_404(Booking, booking_id=booking_id)

    if customer in request.user.customer.all():

        # Delete booking_id from database
        customer.delete()

        # Display successful message to user
        messages.add_message(
            request, messages.SUCCESS,
            'Your booking was successfully cancelled!')

        # Redirect back to booking.html
        return redirect(reverse('bookings:booking'))

    else:

        messages.error(request, 'Sorry, you are not allow on this page!')

        return redirect(reverse('bookings:index'))

webpages/views.py
from django.shortcuts import render

from django.views.generic import (TemplateView)


def contact_us(request):
    return render(request, 'webpages/contact-us.html')


class SaunaSteam(TemplateView):
    template_name = 'webpages/sauna-steam.html'

bookings/templates/bookings/booking.html
{% extends "base.html" %}

{% block title %} Active-Spring| Bookings {% endblock%}

{% block content %}

<div class="container-fluid mb-auto">

  <div class="row d-flex align-items-center p-4">

    <div class="col-lg-12 m-auto w-100">

      <h2 class="text-center">Bookings</h2>

    </div>

  </div>

  {% if user.is_authenticated %}

  <div class="row">

    <div class="col-12">

      <ul class="list-group list-group-horizontal mt-5 w-auto">

        <li class="list-group-item bg-info">

          <a href="{% url 'bookings:create' %}" class="booking-btn text-dark text-center m-auto w-100">Make a
            booking</a>

        </li>

      </ul>

      <hr class="cl-black">

    </div>

  </div>

  <div class="row mt-5">

    {% for customer in page_obj %}

    <div class="col-lg-4" style="overflow-x:auto;">

      <ul class="list-group list-group-horizontal mt-5 w-auto">

        <li class="list-group-item bg-info">

          <a class="text-dark" href="{% url 'bookings:update' customer.booking_id %} "> Update booking</a>

        </li>

        <li class="list-group-item bg-danger">

          <a class="text-dark" data-toggle="modal" data-target="#staticBackdrop">Cancel Booking </a>

        </li>

      </ul>

      <ul class="list-group w-auto text-dark">

        <li class="list-group-item list-group-item-light text-dark">

          <h4>Booking ID</h4>{{ customer.booking_id }}

        </li>

        <li class="list-group-item list-group-item-secondary">

          <h4>Name</h4>{{ customer.name }}

        </li>

        <li class="list-group-item list-group-item-light text-dark">

          <h4>Email</h4>{{ customer.email }}

        </li>

        <li class="list-group-item list-group-item-secondary">

          <h4>No. of Perosns</h4>{{customer.no_of_persons}}

        </li>

        <li class="list-group-item list-group-item-light text-dark">

          <h4>Booking Time</h4>{{customer.booking_time}}

        </li>

        <li class="list-group-item list-group-item-light text-dark">

          <h4>Booking Date</h4>{{customer.booking_date}}

        </li>

        <li class="list-group-item list-group-item-secondary">

          <h4>Booking Status</h4>{{customer.booking_status}}

        </li>

        <li class="list-group-item list-group-item-light text-dark">

          <h4>Booked On</h4>{{customer.booked_on}}

        </li>

      </ul>

    </div>

    <!-- Modal -->

    <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1"
      aria-labelledby="staticBackdropLabel" aria-hidden="true">

      <div class="modal-dialog">

        <div class="modal-content">

          <div class="modal-header">

            <h5 class="modal-title" id="staticBackdropLabel">Are you sure?</h5>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">

              <span aria-hidden="true">&times;</span>

            </button>

          </div>

          <div class="modal-body">

            <p>Are you sure you want to delete the selected booking? This booking is about to be permanently deleted.
            </p>

            <small>Warning! You can't undo this action.</small>

          </div>

          <div class="modal-footer p-0 m-0">

            <div class="col-6 bg-danger m-0">

              <a href="{% url 'bookings:delete' customer.booking_id %}" class=" nav-link navbar-nav text-center p-3">Yes
                I'm Sure</a>

            </div>

            <div class="col-6 cl-silver m-0">

              <a href="{% url 'bookings:booking' %}" class="nav-link navbar-nav text-center p-3">No, take me back</a>

            </div>

          </div>

        </div>

      </div>

    </div>

    <!--/ . Endof Modal -->

    {% endfor %}

  </div>

  <!-- Paginator -->
  <div class="pagination row">

    <div class="col-12 text-center mt-3">

      <span class="step-links">

        {% if page_obj.has_previous %}

        <a href="?page=1">&laquo; First</a>

        <a href="?page={{ page_obj.previous_page_number }}">Previous</a>

        {% endif %}

        <span class="current"> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>

        {% if page_obj.has_next %}

        <a href="?page={{ page_obj.next_page_number }}">Next</a>

        <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>

        {% endif %}

      </span>

    </div>

  </div>

  <!--/ . Endof Paginator -->

  {% else %}

  <div id="myModal" class="modal fade">

    <div class="modal-dialog">

      <div class="modal-content">

        <div class="modal-header">

          <h5 class="modal-title">Sign In or Sign Up to book your swimming slots today!</h5>

          <button type="button" class="close" data-dismiss="modal" aria-label="Close">

            <span aria-hidden="true">&times;</span>

          </button>

        </div>

        <div class="modal-body">

          <p>Get active, Stay active!</p>

        </div>

        <div class="modal-footer p-0 m-0 row">

          <div class="col-sm bg-info btn">

            <a href="{% url 'account_login' %}" class=" nav-link navbar-nav text-center p-3">Sign In</a>

          </div>

          <div class="col-sm bg-info btn">

            <a href="{% url 'account_signup' %}" class=" nav-link navbar-nav text-center p-3">Sign Up</a>

          </div>

        </div>

      </div>

    </div>

  </div>

  <div class="col-12 text-center p-5">

    <h6>You have no bookings</h6>

  </div>

  {% endif %}

</div>

{% endblock content %}

bookings/templates/bookings/create-booking.html
{% extends "base.html" %}

{% block title %} Active-Spring | Create Booking {% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container mb-auto">

    <div class="row d-flex align-items-center p-4">

        <div class="col-lg-12 m-auto w-100">

            <h4 class="text-center"> Create Booking</h4>

        </div>

        <div class="col-md-8 mt-3 offset-md-2 con-form">

            <form method="POST" class="p-3 w-100">

                <!-- Security token -->
                {% csrf_token %}

                {{ form|crispy }}

                <input  type="submit" class="btn enquiry-btn p-1 w-auto" value="Making Booking">

            </form>

        </div>
    </div>

</div>


{% endblock content %}

bookings/templates/bookings/index.html
{% extends "base.html" %}

{% block title %} Active-Spring | Home{% endblock%}

{% block content %}

 <!-- Logo Section-->
 <section class="container-fluid first-bg-image p-0">

     <div class="row m-0">

         <div class="col-lg-8 col-md-12 col-sm-12 text-center">

             <h1 class="welcome-msg bg-black-op rounded">Welcome to Active-Spring swimming Pool

                 <br>

                 <span class="welcome-msg mt-0 pg-text">Our pool, along with the facilities and services we offer,
                     has been ranked among<br>the best in the UK. Book your daily swims today!</span>
             </h1>

         </div>

     </div>

 </section>
 <!-- / .Logo Section-->

 <!-- Pool Ethos (First Article)-->
 <article class="container-fluid p-0">


    <blockquote class="blockquote m-0 p-0">

        <p class="mb-0">"If you haven't failed, you aren't pushing hard enough."</p>

        <footer class="blockquote-footer">ADAM PEATY</footer>

    </blockquote>

    <div class="col-lg-12 col-sm-12 mt-auto mb-auto pool-info">

        <h3 class="text-center"> We at Active-Spring </h3>

        <small> are aware that maintaining your physical fitness is crucial to leading a happy and healthy
             life.
             You may have heard that specialists advise adults to engage in 150 minutes of moderate exercise
             or 75 minutes of intense exercise per week.
             Here at Active-Spring, we follow our passions by using swimming to achieve these goals. Swimming
             is not only fun, but it also has many health benefits.
             Swimming is an excellent way to work your entire body and cardiovascular system. An hour of
             swimming burns almost as many calories as running, without
             all the impact on your bones and joints.
        </small>

    </div>

 </article>
 <!-- / .Pool Ethos (First Article)-->

 <!-- Pool Opening Hours (Second Article) -->
<article class="container-fluid p-0">

    <div class="row p-0 m-auto">

        <div class="col-12 m-auto">

            <h4 class="text-center">Pool Opening Hours</h4>

            <hr class="cl-black">

            <table class="table table-striped text-center">

                <tbody>


                    <tr>

                        <td>Monday</td>
                        <td>08:00</td>
                        <td> 18:00</td>

                    </tr>

                    <tr>

                        <td>Tuesday</td>
                        <td>08:00</td>
                        <td> 18:00</td>

                    </tr>

                    <tr>

                        <td>Wednesday</td>
                        <td>08:00</td>
                        <td> 18:00</td>

                    </tr>

                    <tr>

                        <td>Thursday</td>
                        <td>08:00</td>
                        <td> 18:00</td>

                    </tr>

                    <tr>

                        <td>Friday</td>
                        <td>08:00</td>
                        <td> 18:00</td>

                    </tr>

                    <tr>

                        <td>Saturday</td>
                        <td>08:00</td>
                        <td> 18:00</td>

                    </tr>
                    <tr>

                        <td>Sunday</td>
                        <td>08:00</td>
                        <td> 18:00</td>

                    </tr>

                </tbody>

            </table>

            <hr class="cl-black the-table">

        </div>

    </div>

</article>
 <!-- / .Pool Opening Hours (Second Article) -->

<article class="container-fluid p-0">

    <blockquote class="blockquote m-0 p-0">

        <p class="mb-0">"If there is a dream or a goal that you want, you have to go for it 100%."</p>

        <footer class="blockquote-footer">Alia Atkinson</footer>

    </blockquote>

    <div class="row p-0 m-auto">

        <div class="col-lg-6 col-md-5 col-sm-12 ml-auto p-0">

            <div class="text-center p-3 home-images">

                <img src="https://s9.gifyu.com/images/artem-verbo-rAyIvNqlwCY-unsplash.jpg" alt="Image of an indoor pool.">

            </div>

        </div>

        <div class="col-lg-4 col-md- col-sm-12 mt-5 mb-auto mr-auto">

            <h4 class="text-center">Indoor Pool</h4>

            <hr class="cl-black">

            <small> In our heated indoor pool, feel free to jump in and make a splash. Our indoor pool has a shallow
                end
                and a deep end, with
                a shallow end that is 1.2m deep and a deep end that is 3.8m deep. The pool is approximatley 100m in
                length, 50m in width and has
                a total of ten swimming lanes.
                Up to 120 people can use the pool at once. Each session lasts an hour, and our guests are free to book
                however many sessions
                they require. Once the pool is open, lifeguards are positioned around the pool to keep our guests safe,
                and there are safety
                warnings posted all around the pool that visitors must abide by.
            </small>

        </div>

    </div>

</article>

{% endblock content %}

bookings/templates/bookings/update-booking.html
{% extends 'base.html' %}

{% block title %} Active-Spring | Update Booking {% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container mb-auto">

    <div class="row d-flex align-items-center p-4">

        <div class="col-lg-12 m-auto w-100">

            <h4 class="text-center"> Update Booking</h4>

        </div>

        <div class="col-md-8 mt-3 offset-md-2 con-form">

            <form method="POST" class="p-3 w-100">

                <!-- Security token -->
                {% csrf_token %}

                {{ form|crispy }}

                <input  type="submit" class="btn enquiry-btn p-1 w-auto" value="Update Booking">

            </form>

        </div>

    </div>

</div>

{% endblock content %}

bookings/templates/create-booking.html
{% extends "base.html" %}

{% block title %} Active-Spring swimming pool {% endblock%}

{% block content %}

<form method="POST" action='create'>
 
    <!-- Security token -->
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">
</form>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %} Active-Spring swimming pool {% endblock%}</title>

    <!--Boostrap CSS-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <!--Personal CSS-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!--Fontawesome kit-->
    <script src="https://kit.fontawesome.com/95bc93f676.js" crossorigin="anonymous"></script>

    <!--EmailJs script-->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js">
    </script>
    <script type="text/javascript">
        (function () {
            emailjs.init("XAx_NGI2tj6CUrx52");
        })();
    </script>
    <!-- / .EmailJs script-->
</head>

<body>
    <!-- Header -->
    <header>

        <nav class="navbar navbar-expand-lg navbar-light nav-colour">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">

                <span class="navbar-toggler-icon"></span>

            </button>

            <a href="{% url 'bookings:index'%}" class=" navbar-brand the-logo mb-0 top-fixed"> Active<i class="fa-solid fa-bolt"></i>Spring</a>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">

                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">

                    <li class="nav-item active">

                        <a href="{% url 'bookings:index' %}" class="nav-link hvr-underline-from-center">Home<span class="sr-only">(current)</span></a>

                    </li>

                    <li class="nav-item active">

                        <a href="{% url 'bookings:booking' %}" class="nav-link hvr-underline-from-center">Bookings<span class="sr-only">(current)</span></a>

                    </li>

                    <li class="nav-item active">

                        <a href="{% url 'webpages:sauna-steam' %}" class="nav-link hvr-underline-from-center">Sauna and Steam</a>

                    </li>

                    <li class="nav-item active">
                        
                        <a href="{% url 'webpages:contact-us' %}" class="nav-link hvr-underline-from-center">Contact Us</a>

                    </li>

                    {% if user.is_authenticated %}

                    <li class="nav-item active">

                        <a href="{% url 'account_logout' %}" class="nav-link hvr-underline-from-center d-lg-none">Sign Out</a>

                    </li>

                    {% else %}

                    <li class="nav-item active">

                        <a href="{% url 'account_login' %}" class="nav-link hvr-underline-from-center d-lg-none">Sign In</a>

                    </li>

                    <li class="nav-item active">

                        <a href="{% url 'account_signup' %}" class="nav-link hvr-underline-from-center d-lg-none">Sign Up</a>

                    </li>
                    
                    {% endif %}
                </ul>

                <div id="hide">

                    {% if user.is_authenticated %}

                    <a href="{% url 'account_logout' %}" class=" nav-link navbar-nav p-2 register-btn ml-1  d-inline text-center">Sign Out</a>

                    {% else %}

                    <a href="{% url 'account_login' %}" class=" nav-link navbar-nav p-2 register-btn ml-1  d-inline text-center">Sign In</a>

                    <a href="{% url 'account_signup' %}" class=" nav-link navbar-nav p-2 register-btn ml-1  d-inline text-center">Sign Up</a>

                    {% endif%}

                </div>

            </div>

        </nav>

        <div class="container">

            <div class="row">

                <div class="col-md-8 offset-md-2 text-center">

                    {% for message in messages %}

                    <div class="alert {{ message.tags }} alert dismissable fade show" id="msg" role="alert">

                        {{ message | safe }}

                    </div>

                    {% endfor %}

                </div>

            </div>

        </div>

    </header>

    <!-- / .Header -->

    {% block content %}

    <!-- Content goes here! -->

    {% endblock content %}

    <!-- Footer -->
    <footer class="container-fluid mt-3">

        <div class="row">

            <div class="mr-auto d-block p-3">

                <h4 class="text-center">Our Location</h4>

                <hr class="mt-0 cl-black">

                <p> Active Spring Road, Newforest, MO30 4HT </p>

            </div>

            <div class="ml-auto d-block p-3">

                <h4 class="text-center">Our Social</h4>

                <hr class="mt-0 cl-black">

                <div class="social-media">

                    <a href="https://www.instagram.com/" target="_blank" class="foot-link ml-2"><i class="fa-brands fa-square-instagram hvr-bounce-in"></i></a>

                    <a href="https://en-gb.facebook.com/" target="_blank" class="foot-link ml-2"><i class="fa-brands fa-square-facebook hvr-bounce-in"></i></a>

                    <a href="https://www.linkedin.com/in/joha-wilson-5075a8249/s" target="_blank" class="foot-link ml-2"><i class="fa-brands fa-linkedin hvr-bounce-in"></i></a>

                    <a href="https://github.com/Joha-will?tab=repositories" target="_blank" class="foot-link ml-2"><i class="fa-brands fa-github hvr-bounce-in"></i></a>

                </div>

            </div>

        </div>

        <hr class="mt-0 cl-black">

        <div class="text-center">

            <small>&copy; Copyright 2020. Joha Wilson. This project is made for educational purposes only. No commercial revenue is generated from the project.</small>

        </div>
        
    </footer>
    <!--/ .Footer-->

    <!-- bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
        integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous">
    </script>

    <!-- Personal JS -->
    <script src="{% static 'js/send-email.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>

    <!-- Timer for displayed messages -->
    <script>
        setTimeout(function () {
            let messages = document.getElementById("msg");
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3000);
    </script>

</body>

</html>

webpages/templates/webpages/contact-us.html
{% extends "base.html" %}

{% block title %} Active-Spring| Contact Us {% endblock%}

{% block content %}

<div class="container-fluid contact-bg-image mb-auto">

    <div class="row">

        <div class="col-lg-4 mt-4 ml-auto">

            <h2> Contact Us</h2>

            <hr class="cl-black">

            <small>If you have any enquires, please fill out the form and we would be happy to help.</small>

            <div class="col-lg-10 col-md-5 col-sm-12 m-auto p-0">

                <div class="text-center p-3 home-images">

                    <img src="https://s9.gifyu.com/images/raj-rana-ttzU0sZmkpA-unsplash.jpg" alt="Image of a little girl splashing in a pool.">

                </div>

            </div>

        </div>

        <div class="col-lg-5 con-form">

            <form onsubmit="return sendMail(this);" method="POST">

                {% csrf_token %}

                <br>

                <label for="fullname">Name</label>

                <input type="text" name="name" class="form-control" id="fullname" placeholder="Enter your full name" required>

                <label for="email">Email</label>

                <input type="email" name="email" class="form-control" id="email" placeholder="email@example.com" required>

                <label for="commentbox">Enquiry or Comment</label>

                <textarea class="form-control" name="commentbox" id="commentbox" rows="10" required></textarea>

                <button type="submit" class="btn enquiry-btn p-1 w-auto"> Enquire Now</button>

            </form>

        </div>

        <!-- Modal -->
        <div class="modal fade my-modal" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">

            <div class="modal-dialog">

                <div class="modal-content">

                    <div class="modal-header grad">

                        <h5 class="modal-title" id="staticBackdropLabel">"</h5>

                    </div>

                    <div class="modal-body grad">

                    </div>

                    <div id="change-color" class="modal-footer">

                        <a href="{% url 'bookings:index' %}" class=" nav-link navbar-nav p-2 return-home-btn ml-1  d-inline text-center">Return Home </a>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>

{% endblock %}